### ISSUE TITLE
inclusion criteria (constipation) is not the drug target (pain)

### ISSUE THREAD

**Issue by bill-baumgartner** [multiomicsKP/clinical_trials_kp#4]
https://clinicaltrials.gov/study/NCT00513656?tab=table

Although `constipation` is listed in the `conditions` field, it appears as though constipation is part of the inclusion criteria while the trial is really about treating pain from cancer.

**Comment by gglusman** [comment]
I'm not sure I'd interpret it that way. Bowel Function Index is listed as one of the Outcome Measures. One of the resulting publications is also about bowel function.
